import test from 'node:test';
import assert from 'node:assert/strict';
import {makeWorld} from '../src/domain/world.js';
import {enableAdvancedCareer} from '../src/domain/advanced-career.js';
import {enableCareerPersonality,personalityEnabled,validateCareerPersonality,syncCareerPersonality,recordCareerPersonalityEvent,applyCareerMoraleAdjustment,settleCareerPersonalityRound,settleCareerPersonalitySeason,lockerRoomView} from '../src/domain/career-personality.js';
import {generatePersonality} from '../src/addons/domain/player-personality.mjs';
import {initialPlayerDynamics,playerInfluence,applyPlayerEvent,validateDynamics,inspectLockerRoom} from '../src/addons/domain/player-locker-room.mjs';

const setup=()=>{
 const w=makeWorld(1692,'IT');w.clubId=w.teams[0].id;
 enableAdvancedCareer(w);enableCareerPersonality(w);
 w.lineup=w.players.filter(p=>p.clubId===w.clubId).slice(0,11).map(p=>p.id);
 assert.equal(validateCareerPersonality(w),true);
 return w;
};
test('PLYR-06.2: schema v2 has one authoritative morale and seven trait leadership',()=>{
 const w=setup(),p=w.players.find(p=>p.clubId===w.clubId),st=w.advancedV1.personalityV1.playerStates[String(p.id)];
 assert.equal(st.schemaVersion,2);
 assert.equal(w.advancedV1.personalityV1.schemaVersion,2);
 assert.equal(st.morale,p.morale);
 const profile=generatePersonality({id:p.id,globalId:p.globalId},{seed:w.seed,countryId:w.countryId});
 const other=structuredClone(profile);other.traits.leadership=other.traits.leadership===100?1:100;
 assert.notEqual(playerInfluence(p,profile),playerInfluence(p,other));
 assert.equal(validateDynamics(st),true);
 assert.equal(personalityEnabled(w),true);
});
test('event ledger is bounded, immutable, rejects invalid data and deduplicates IDs beyond history view',()=>{
 const w=setup(),p=w.players.find(p=>p.clubId===w.clubId),profile=p.personalityProfile;
 const first=initialPlayerDynamics(p),clone=structuredClone(first);
 const next=applyPlayerEvent(first,profile,{id:'E1',type:'coach_criticism'});
 assert.deepEqual(first,clone);
 assert.equal(applyPlayerEvent(next,profile,{id:'E1',type:'coach_criticism'}).revision,next.revision);
 assert.equal(next.history.length,1);assert.ok(next.coachRelationship<50);
 assert.throws(()=>applyPlayerEvent(next,profile,{id:'E2',type:'contract_promise',moraleDelta:200}),/DELTA/);
 assert.throws(()=>applyPlayerEvent(next,profile,{id:'E2',type:'played',moraleDelta:1}),/DELTA/);
 assert.throws(()=>applyPlayerEvent(next,profile,{id:'E3',type:'bad'}),/EVENT/);
 let state=next;for(let i=0;i<110;i++)state=applyPlayerEvent(state,profile,{id:'training-'+i,type:'training',importance:0});
 assert.equal(state.history.length,100);
 assert.equal(applyPlayerEvent(state,profile,{id:'E1',type:'played'}).revision,state.revision);
});
test('real match IDs gate round events, draws have exactly one participation event',()=>{
 const w=setup(),s=w.advancedV1.personalityV1,players=w.players.filter(p=>p.clubId===w.clubId);
 const p=players[0],before=s.playerStates[String(p.id)];
 w.round=1;
 const beforeMorale=p.morale;
 assert.equal(settleCareerPersonalityRound(w,{matchId:'match-17',result:'draw',playedIds:[p.id]}),true);
 const after=s.playerStates[String(p.id)];
 assert.equal(after.history.length,1);
 assert.equal(after.history[0].type,'played');
 assert.equal(p.morale,after.morale);
 assert.notEqual(p.morale,beforeMorale);
 const saved=JSON.stringify(w);
 assert.equal(settleCareerPersonalityRound(w,{matchId:'match-17',result:'draw',playedIds:[p.id]}),false);
 assert.equal(JSON.stringify(w),saved);
 assert.equal(s.processedMatches.length,1);
 assert.equal(validateCareerPersonality(w),true);
});
test('win and loss produce bounded outcome plus participation, never double count',()=>{
 const w=setup(),s=w.advancedV1.personalityV1,p=w.players.find(p=>p.clubId===w.clubId);
 w.round=1;
 assert.equal(settleCareerPersonalityRound(w,{matchId:'game-1',result:'win',playedIds:[p.id]}),true);
 const first=s.playerStates[String(p.id)];
 assert.deepEqual(first.history.map(x=>x.type),['win','played']);
 assert.equal(settleCareerPersonalityRound(w,{matchId:'game-1',result:'win',playedIds:[p.id]}),false);
 w.round=2;
 assert.equal(settleCareerPersonalityRound(w,{matchId:'game-2',result:'loss',playedIds:[]}),true);
 const second=s.playerStates[String(p.id)];
 assert.deepEqual(second.history.map(x=>x.type),['win','played','loss','bench']);
 assert.equal(second.morale,p.morale);
 assert.equal(validateCareerPersonality(w),true);
});
test('explicit coach decision event adjusts morale and trust exactly once',()=>{
 const w=setup(),s=w.advancedV1.personalityV1,p=w.players.find(p=>p.clubId===w.clubId);
 assert.equal(recordCareerPersonalityEvent(w,{playerId:p.id,eventId:'decision-123',type:'coach_praise'}),true);
 const st=s.playerStates[String(p.id)],saved=JSON.stringify(w);
 assert.equal(recordCareerPersonalityEvent(w,{playerId:p.id,eventId:'decision-123',type:'coach_praise'}),false);
 assert.equal(JSON.stringify(w),saved);
 assert.ok(st.coachRelationship>50);
 assert.equal(st.morale,p.morale);
 assert.equal(validateCareerPersonality(w),true);
});
test('manager changes reset relationship without a morale bonus, exactly once',()=>{
 const w=setup(),s=w.advancedV1.personalityV1,p=w.players.find(p=>p.clubId===w.clubId);
 recordCareerPersonalityEvent(w,{playerId:p.id,eventId:'critique-1',type:'coach_criticism'});
 const baseline=p.morale;
 assert.notEqual(s.playerStates[String(p.id)].coachRelationship,50);
 w.manager='Another Coach';
 assert.equal(syncCareerPersonality(w),true);
 assert.equal(s.playerStates[String(p.id)].coachRelationship,50);
 assert.equal(p.morale,baseline);
 const saved=JSON.stringify(w);
 assert.equal(syncCareerPersonality(w),false);
 assert.equal(JSON.stringify(w),saved);
 assert.equal(validateCareerPersonality(w),true);
});
test('club appointment reconciles squad, removes stale entries, leaves stable personality unchanged',()=>{
 const w=setup(),s=w.advancedV1.personalityV1;
 const former=w.players.find(p=>p.clubId===w.clubId),profile=structuredClone(former.personalityProfile);
 const nextClub=w.teams[1].id;
 w.clubId=nextClub;
 assert.equal(syncCareerPersonality(w),true);
 assert.ok(!s.playerStates[String(former.id)]);
 const p=w.players.find(p=>p.clubId===nextClub);
 assert.equal(s.playerStates[String(p.id)].coachRelationship,50);
 w.clubId=former.clubId;
 syncCareerPersonality(w);
 assert.deepEqual(former.personalityProfile,profile);
 assert.equal(validateCareerPersonality(w),true);
});
test('official contract adjustment and season reset retain a single morale value',()=>{
 const w=setup(),s=w.advancedV1.personalityV1,p=w.players.find(p=>p.clubId===w.clubId);
 const old=p.morale;
 assert.equal(applyCareerMoraleAdjustment(w,{playerId:p.id,eventId:'promise-1',delta:-4}),true);
 assert.equal(p.morale,Math.max(0,old-4));
 assert.equal(s.playerStates[String(p.id)].morale,p.morale);
 assert.equal(applyCareerMoraleAdjustment(w,{playerId:p.id,eventId:'promise-1',delta:-4}),false);
 const count=s.events.length;
 p.morale=Math.min(95,p.morale+12);w.season++;
 settleCareerPersonalitySeason(w);
 assert.equal(s.playerStates[String(p.id)].morale,p.morale);
 assert.equal(s.events.length,count);
 assert.equal(validateCareerPersonality(w),true);
});
test('leadership changes influence and group weighting but never teammates morale',()=>{
 const w=setup(),p=w.players.filter(p=>p.clubId===w.clubId).slice(0,3);
 const old=p.map(x=>x.morale);
 const a=inspectLockerRoom(p);
 const b=lockerRoomView(w);
 assert.equal(a.count,3);
 assert.equal(b.count,w.players.filter(x=>x.clubId===w.clubId).length);
 assert.ok(b.leaders.length===3&&b.leaders[0].influence>=b.leaders[1].influence);
 assert.deepEqual(p.map(x=>x.morale),old);
});
test('serialization preserves events and reprocessing prevents replay after restart',()=>{
 const w=setup(),p=w.players.find(p=>p.clubId===w.clubId);
 w.round=1;settleCareerPersonalityRound(w,{result:'win',matchId:'season:fixture:22',playedIds:[p.id]});
 const saved=structuredClone(w);
 const before=JSON.stringify(saved);
 assert.equal(settleCareerPersonalityRound(saved,{result:'win',matchId:'season:fixture:22',playedIds:[p.id]}),false);
 assert.equal(JSON.stringify(saved),before);
 assert.equal(validateCareerPersonality(saved),true);
});
