/** WRD03 national cup brackets, current scorers, awards and official honours. */
import {cupsEnabled,cupForCountry,cupHonours} from '../domain/career-cups.js';
import {careerWorldLeague} from '../domain/career-world.js';
import {esc} from '../ui-components.js';
import {displayCareerMoney} from '../domain/career-locale.js';
const t=(en,it,english)=>en?english:it;
export function nationalCupPanel(w,ui,country){
 const en=ui.language==='en';
 if(!cupsEnabled(w))return `<section class="panel cup-panel" aria-label="${t(en,'Coppe nazionali','National cups')}"><h2>${t(en,'Coppe nazionali','National cups')}</h2><p>${t(en,'Attiva otto coppe nazionali di fantasia con sorteggi, supplementari, rigori, premi e albo d’oro. Le giornate di campionato non vengono sostituite.','Enable eight fictional national cups with draws, extra time, penalties, prizes and honours. League fixtures remain unchanged.')}</p><button type="button" class="btn btn-primary" data-action="enable-cups">${t(en,'Attiva coppe nazionali','Enable national cups')}</button></section>`;
 const state=w.advancedV1.cupsV1;
 if(state.deferred)return `<section class="panel cup-panel" aria-label="${t(en,'Coppe nazionali','National cups')}"><h2>${t(en,'Coppe nazionali','National cups')}</h2><p>${t(en,'Attivazione confermata: la prima coppa inizierà dalla prossima stagione perché il turno preliminare è già trascorso.','Enabled: the first cup starts next season, as the preliminary matchday has already passed.')}</p></section>`;
 const cup=cupForCountry(w,country),l=careerWorldLeague(w,country),name=id=>l?.clubs.find(c=>c.id===id)?.name??String(id);
 if(!cup)return '';
 const money=value=>displayCareerMoney(value,{countryId:country,lang:ui.language});
 const scorers=cup.scorers.slice().sort((a,b)=>b.goals-a.goals||a.name.localeCompare(b.name)).slice(0,8);
 const history=cupHonours(w,country).slice(-12).reverse();
 const rowMatch=m=>{const r=m.result,score=r?`${r.homeGoals}–${r.awayGoals}${r.extraTime?` (${r.extraTime.homeGoals}–${r.extraTime.awayGoals} ${t(en,'supp.','ET')})`:''}${r.penalties?` (${r.penalties.home}–${r.penalties.away} ${t(en,'rig.','pens')})`:''}`:'—';return `<tr><td>${esc(name(m.home))}</td><td><strong>${esc(score)}</strong></td><td>${esc(name(m.away))}</td><td>${r?esc(name(r.winnerId)):'—'}</td></tr>`;};
 return `<section class="panel cup-panel" aria-label="${t(en,'Coppe nazionali','National cups')}"><div class="cup-header"><div><span class="overline">${t(en,'COPPA NAZIONALE','NATIONAL CUP')}</span><h2>${esc(en?({IT:'Towers Cup',ENG:'Counties Cup',ES:'Sun Cup',DE:'Cities Cup',FR:'Cities Cup',NL:'Cities Cup',PT:'Stars Cup',BR:'Stars Cup'}[country]):cup.name)}</h2><p>${t(en,'Stagione','Season')} ${cup.season} · ${cup.participants.length} ${t(en,'partecipanti','entrants')} · ${t(en,'Turni infrasettimanali separati','Separate midweek cup slots')}</p></div><span class="cup-trophy" aria-hidden="true">🏆</span></div>
 ${cup.championId?`<p class="cup-champion">${t(en,'Campione','Winner')}: <strong>${esc(name(cup.championId))}</strong></p>`:''}
 <div class="cup-bracket">${cup.rounds.map((round,i)=>`<article class="cup-round"><h3>${i===cup.calendar.length-1?t(en,'Finale','Final'):i===0&&cup.participants.length>16?t(en,'Preliminari','Preliminary'):t(en,'Turno','Round')+' '+(i+1)}</h3><p>${t(en,'Dopo giornata','After league matchday')} ${round.leagueRound}</p>${round.byes.length?`<p>${t(en,'Passano senza giocare','Byes')}: ${round.byes.map(id=>esc(name(id))).join(' · ')}</p>`:''}<div class="table-scroll" tabindex="0" role="region" aria-label="${t(en,'Tabellone','Cup bracket')} ${i+1}"><table class="data-table"><thead><tr><th>${t(en,'Casa','Home')}</th><th>${t(en,'Risultato','Score')}</th><th>${t(en,'Trasferta','Away')}</th><th>${t(en,'Qualificata','Winner')}</th></tr></thead><tbody>${round.matches.map(rowMatch).join('')}</tbody></table></div></article>`).join('')}</div>
 <div class="cup-summaries"><div><h3>${t(en,'Marcatori di coppa','Cup scorers')}</h3><div class="table-scroll" tabindex="0" role="region"><table class="data-table"><thead><tr><th>${t(en,'Giocatore','Player')}</th><th>${t(en,'Reti','Goals')}</th></tr></thead><tbody>${scorers.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.goals}</td></tr>`).join('')||'<tr><td colspan="2">—</td></tr>'}</tbody></table></div></div><div><h3>${t(en,'Premi assegnati','Prizes awarded')}</h3><p>${cup.awards.length} ${t(en,'premi di qualificazione','advancement awards')} · ${money(cup.awards.reduce((n,a)=>n+a.amountEUR,0))}</p><h3>${t(en,'Albo d’oro','Honours')}</h3><div class="table-scroll" tabindex="0" role="region"><table class="data-table"><thead><tr><th>${t(en,'Stagione','Season')}</th><th>${t(en,'Vincitrice','Champion')}</th></tr></thead><tbody>${history.map(h=>`<tr><td>${h.season}</td><td>${esc(name(h.championId))}</td></tr>`).join('')||'<tr><td colspan="2">—</td></tr>'}</tbody></table></div></div></div>
 <p class="muted small">${t(en,'Simulazione fittizia seedata: supplementari 91–120, rigori soltanto in parità. Premi esteri differiti finché il relativo conto mercato non è disponibile.','Deterministic fictional simulation: extra time at 91–120, penalties for ties only. Foreign awards are held until corresponding market finance accounts exist.')}</p></section>`;
}
